_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "weight/R-101.pkl"
  RESNET_BOVW: "configs/ResNet101.yaml"
  BOVW_WEIGHT: "weight/coco/pabovw/model_best.pth"
  NUM_WORDS: 1024
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "BoVWROIHeads"
    NUM_CLASSES: 60
    CLS_WEIGHT: 0.7
    BOW_IOU_THRESHOLD: 0.8
DATASETS:
  TRAIN: ('coco_trainval_base',)
  TEST: ('coco_test_base',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (140000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 40000
OUTPUT_DIR: "checkpoints/coco/bovw/base"
